New log file opened at Fri May 01 12:59:22 CEST 2015 by 5104@Felix-PC
Taking next connection to: 55809
New client attempting to connect on port: 55813-55809
  Address = /192.168.178.33:55809
This client on port 55813 has uuid edeec9f8-66a0-444e-8b3b-31e31c2e8d50 configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-edeec9f8-66a0-444e-8b3b-31e31c2e8d50
Taking next connection to: 55809
New client attempting to connect on port: 55814-55809
  Address = /192.168.178.33:55809
Handshake exception on socket: 55814
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 55809
New client attempting to connect on port: 55815-55809
  Address = /192.168.178.33:55809
This client on port 55815 has uuid 8d91c8ac-1b9c-4472-9716-6b6c21002938 configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-edeec9f8-66a0-444e-8b3b-31e31c2e8d50, activator-8d91c8ac-1b9c-4472-9716-6b6c21002938
Taking next connection to: 55809
New client attempting to connect on port: 55977-55809
  Address = /192.168.178.33:55809
Handshake exception on socket: 55977
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 55809
New client attempting to connect on port: 55978-55809
  Address = /192.168.178.33:55809
This client on port 55978 has uuid baa0352e-cca0-4022-bdc6-1bfd40442c81 configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-8d91c8ac-1b9c-4472-9716-6b6c21002938, play-fork-run-baa0352e-cca0-4022-bdc6-1bfd40442c81
Taking next connection to: 55809
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 55809
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 55809
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 55809
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 55809
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 55809
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 55809
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 55809
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 55809
